substitutions:
  _VERSION: "1.0"
steps:
  - name: gcr.io/cloud-builders/docker
    id: "Build: Docker Image"
    args:
      - "build"
      - "--build-arg"
      - "var_version=:${_VERSION}"
      - "--build-arg"
      - "var_commitsha=$COMMIT_SHA"
      - "--tag=gcr.io/${PROJECT_ID}/flask-api:${_VERSION}"
      - "."
images:
  - 'gcr.io/$PROJECT_ID/flask-api:${_VERSION}'